In [1]:
import torch
from torch.autograd import Variable

In [2]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)
print(x)

tensor([-0.7879,  0.9201, -1.3150], requires_grad=True)


In [3]:
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ -806.8121,   942.2013, -1346.5702], grad_fn=<MulBackward0>)


In [4]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

In [5]:
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [6]:
from torch import nn, optim
import torchvision

In [7]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

In [8]:
model = torchvision.models.resnet18(pretrained=True)

C:\Users\Aayush\anaconda3\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\Aayush\anaconda3\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\Aayush/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth


100%|██████████| 44.7M/44.7M [00:04<00:00, 11.5MB/s]


In [9]:
# Freeze all the parameters in the network
for param in model.parameters():
    param.requires_grad = False

In [10]:
model.fc = nn.Linear(512, 10)

In [11]:
# Optimize only the classifier
optimizer = optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [12]:
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0.9
    nesterov: False
    weight_decay: 0
)
