In [1]:
import torch

In [2]:
# simple operation rehash
u = torch.tensor([2, 4])
v = torch.tensor([1, 4])
w = u * v
print(w)
print(w.shape)
print(w.ndim)

tensor([ 2, 16])
torch.Size([2])
1


In [3]:
# broadcasting rules 
a =     torch.ones(4, 3, 2)
b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

tensor([[[0.1443, 0.2164],
         [0.2439, 0.1538],
         [0.8581, 0.3757]],

        [[0.1443, 0.2164],
         [0.2439, 0.1538],
         [0.8581, 0.3757]],

        [[0.1443, 0.2164],
         [0.2439, 0.1538],
         [0.8581, 0.3757]],

        [[0.1443, 0.2164],
         [0.2439, 0.1538],
         [0.8581, 0.3757]]])


In [4]:
c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

tensor([[[0.8479, 0.8479],
         [0.5870, 0.5870],
         [0.6021, 0.6021]],

        [[0.8479, 0.8479],
         [0.5870, 0.5870],
         [0.6021, 0.6021]],

        [[0.8479, 0.8479],
         [0.5870, 0.5870],
         [0.6021, 0.6021]],

        [[0.8479, 0.8479],
         [0.5870, 0.5870],
         [0.6021, 0.6021]]])


In [5]:
d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.2493, 0.8249],
         [0.2493, 0.8249],
         [0.2493, 0.8249]],

        [[0.2493, 0.8249],
         [0.2493, 0.8249],
         [0.2493, 0.8249]],

        [[0.2493, 0.8249],
         [0.2493, 0.8249],
         [0.2493, 0.8249]],

        [[0.2493, 0.8249],
         [0.2493, 0.8249],
         [0.2493, 0.8249]]])


In [6]:
# switch between ndarrays and PyTorch tensors
import numpy as np
numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
# reverse example of converting from PyTorch tensor into ndarray
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.0544, 0.8057, 0.6331],
        [0.8373, 0.7599, 0.6516]])
[[0.05441862 0.8057434  0.6330911 ]
 [0.8372871  0.75994647 0.6516467 ]]


In [8]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.05441862  0.8057434   0.6330911 ]
 [ 0.8372871  17.          0.6516467 ]]
