In [1]:
import torch

In [3]:
#creating some tensors
t0 = torch.tensor(1000) #0-D tensor
t1 = torch.tensor([9, 8, 7, 6]) #1-D tensor
t2 = torch.tensor([[1,2,3],[7,5,3]]) #2-D tensor

print(t0)
print(t1)
print(t2)

tensor(1000)
tensor([9, 8, 7, 6])
tensor([[1, 2, 3],
        [7, 5, 3]])


In [4]:
a = torch.ones((2,3), dtype= torch.int16)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [5]:
#Different datatypes in torch
""" Tensor data types
torch.bool
torch.int8
torch.uint8
torch.int16
torch.int32
torch.int64
torch.half
torch.float
torch.double
torch.bfloat
"""

' Tensor data types\ntorch.bool\ntorch.int8\ntorch.uint8\ntorch.int16\ntorch.int32\ntorch.int64\ntorch.half\ntorch.float\ntorch.double\ntorch.bfloat\n'

In [6]:
print(a.shape)
print(a.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [7]:
#print tensor dimension
print(a.ndimension())
print(a.ndim)

2
2
