In [40]:
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import keras
import numpy as np
advertising_df = pd.read_csv("../Neural Network/Advertising_2023.csv",index_col=0)

In [41]:
advertising_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1199 entries, 1 to 1197
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   digital    1199 non-null   float64
 1   TV         1199 non-null   float64
 2   radio      1199 non-null   float64
 3   newspaper  1199 non-null   float64
 4   sales      1199 non-null   float64
dtypes: float64(5)
memory usage: 56.2 KB


In [42]:
advertising_df.shape

(1199, 5)

In [43]:
#the isnull() method is used to check and manage null values in a data frame
advertising_df.isnull().sum()

digital      0
TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [44]:
X = advertising_df[['digital', 'TV', 'radio', 'newspaper']]
y = advertising_df[['sales']]

In [45]:
normalized_feature = keras.utils.normalize(X.values)
print(normalized_feature)

[[0.89211961 0.4032179  0.0977028  0.17886333]
 [0.66254734 0.45658693 0.39008405 0.44765371]
 [0.29009225 0.20576311 0.51609436 0.77920128]
 ...
 [0.06744611 0.99272247 0.05163843 0.08536149]
 [0.19480049 0.91868871 0.08898294 0.33188231]
 [0.06744611 0.99272247 0.05163843 0.08536149]]


In [46]:
from sklearn.model_selection import train_test_split

X_train,X_test, y_train,y_test = train_test_split(X,y, test_size=0.4, random_state=101)

In [47]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(719, 4) (480, 4) (719, 1) (480, 1)


In [48]:
model = Sequential()
model.add(Dense(4, activation="relu"))
model.add(Dense(3, activation="relu"))
model.add(Dense(1))

In [49]:
model.compile(optimizer="adam", loss="mse", metrics=["mse"])

In [50]:
history =model.fit(X_train,y_train, validation_data = (X_test, y_test), epochs = 32)

Epoch 1/32
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 115.3840 - mse: 115.3840 - val_loss: 78.5767 - val_mse: 78.5767
Epoch 2/32
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.0110 - mse: 66.0110 - val_loss: 54.2158 - val_mse: 54.2158
Epoch 3/32
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.2196 - mse: 47.2196 - val_loss: 37.7892 - val_mse: 37.7892
Epoch 4/32
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 32.2594 - mse: 32.2594 - val_loss: 27.0811 - val_mse: 27.0811
Epoch 5/32
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.0496 - mse: 21.0496 - val_loss: 19.8970 - val_mse: 19.8970
Epoch 6/32
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.3071 - mse: 16.3071 - val_loss: 15.0241 - val_mse: 15.0241
Epoch 7/32
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.3619 - mse: 12.3619 - val_loss: 11.8844 - val_mse: 11.8844
Epoch 8/32
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.1628 - mse: 10.1628 - val_loss: 9.7534 - val_mse: 9.7534
Epoch 9/32
23/23 ━━━━━━━━━━━━━━━━━━━━ 0

In [51]:
test_predictions= model.predict(X_test).flatten()
print(test_predictions)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
[26.338903  18.871262  16.21418   22.214994  17.104307  26.099936
 12.340547  21.24848   18.764544  14.648035   6.417047  16.43935
  5.0201006  8.040227  10.375754   6.5115933 22.212637  15.691591
  3.356727  17.729292  22.421083   6.106065  11.508493  11.736318
  8.230556   2.8094711 14.480036  17.268297  11.6906805 11.006479
 14.646374  17.30362   20.077806  15.61987   19.667458  11.414293
 24.68656   15.335747  12.703423  17.951925  15.617473  14.8382435
  7.294542  15.691201  14.650194  14.48119    6.670537  24.68656
 14.726411   9.018759   8.989531  10.375754  11.352779  15.93959
  3.6546645 18.231188  16.735292  21.59884    8.713801  12.774889
 12.647983  11.689016  12.711026  13.462107   7.974431  12.819428
  8.990612  21.597298   6.561641  22.589956   6.4171467 23.657797
  7.295147  20.161406  13.972152  16.394594  18.079271  13.43915
 17.30362   20.407862  17.798695  19.38002   17.730215  16.984623
 16.393816  19.771492  11.361182   9.01

In [52]:
true_predicted = pd.DataFrame(list(zip(y_test, test_predictions)), columns=["True Value", "Predicted Value"])
true_predicted.head()

True Value  Predicted Value
0      sales        26.338903

In [57]:

from sklearn.metrics import mean_squared_error
import numpy as np

pred_train = model.predict(X_train)
rmse = np.sqrt(mean_squared_error(y_train, pred_train))
print(rmse)

pred = model.predict(X_test)
rmse1 = np.sqrt(mean_squared_error(y_test, pred))
print(rmse1)

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
1.7376091161262208
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
1.8254485140926735
